### ISSUE TITLE
Do we want to have a couple books show up in the shopping cart?

### ISSUE THREAD

**Issue by CraigBryan** [charle692/bookstore#23]
That way the TA can see what the shopping cart actually looks like with things in it? Also, we could carry those things in the shopping cart over to the checkout area and it'll look pretty real.

**Comment by charle692** [comment]
Yup sure that's a good idea.

**Comment by CraigBryan** [comment]
Ok. Expect a PR for this tomorrow then.

**Comment by charle692** [comment]
ok sounds good.
